### ISSUE TITLE
Error searching for ortholog groups by UniProt id

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_rest_api#126]
Example 500 error

https://testapi.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=P00367&from_=0&size=10&fields=orthodb_id&fields=orthodb_name&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number

**Comment by jonrkarr** [comment]
I believe this should lead to a search result for 692851at2759

**Comment by lzy7071** [comment]
This has been fixed.

**Comment by jonrkarr** [comment]
The example above still doesn't work. Do I need to wait for the API to be re-deployed?

**Comment by lzy7071** [comment]
Let me rerun the workflow to build a new container and deploy.

**Comment by jonrkarr** [comment]
No worries about re-deployed after each change. I can come back to this later tonight or tomorrow.

**Comment by jonrkarr** [comment]
Looks good
